version: "3.7"

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--entrypoints.web.address=:80" # Port HTTP
      - "--providers.docker=true" # Active la détection automatique des conteneurs Docker
      - "--api.dashboard=true" # Active le tableau de bord Traefik
    ports:
      - "80:80" # Port HTTP
      - "8080:8080" # Tableau de bord Traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # Nécessaire pour détecter les conteneurs Docker

  order-service:
    build:
      context: ./microservice_order # Assure-toi d’avoir un Dockerfile dans ce dossier
    labels:
      - "traefik.http.routers.node.rule=PathPrefix(`/order`)"
      - "traefik.http.services.node.loadbalancer.server.port=3000" # Port exposé par ton service Node.js

  product-service:
    build:
      context: ./microservice_product # Assure-toi d’avoir un Dockerfile dans ce dossier
    labels:
      - "traefik.http.routers.java.rule=PathPrefix(`/product`)"
      - "traefik.http.services.java.loadbalancer.server.port=8080" # Port exposé par ton service Java

  user-service:
    build:
      context: ./usermanagerms # Assure-toi d’avoir un Dockerfile dans ce dossier
    labels:
      - "traefik.http.routers.node.rule=PathPrefix(`/user`)"
      - "traefik.http.services.node.loadbalancer.server.port=4000" # Port exposé par ton service Node.js
