version: "3.8"

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      JWT_SECRET: "supersecretkey" # Remplacez par votre clé secrète
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongo-data: # Volume Docker pour persister les données de MongoDB
